// BeatBox - Music Database containing the 19 audio tracks
const songs = [
  {
    id: "pavazha-malli-orig",
    title: "Pavazha Malli",
    artist: "Sai Abhyankkar",
    album: "Pavazha Malli - Single",
    duration: "4:01",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293186/Pavazha_Malli_juefjg.mp3",
    cover: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=300&h=300&fit=crop&q=80",
    color: "#1b4f35",
    category: "Sai Abhyankkar Hits",
    liked: false,
    lyrics: [
      { time: 0, text: "🎵 Pavazha Malli - Sai Abhyankkar 🎵" },
      { time: 5, text: "Oru maalai neram... mazhai saarum podhu..." },
      { time: 10, text: "Un vizhiyai paarthu nan vizhithu ponene..." },
      { time: 16, text: "Pavazha malli vaasam un koonthalil veesiyadho..." },
      { time: 22, text: "En nenjil un kaadhal puthu sangeetham paadiyadho..." },
      { time: 29, text: "Sollaamale vanthaai, en ninaivil nindraai..." },
      { time: 35, text: "Un kaadhalil ennaiyae nan tholaithu nindrenae..." },
      { time: 42, text: "🎵 [Melodic Violin Instrumental] 🎵" },
      { time: 55, text: "Pavazha Malli... en paatai nee kelamma..." },
      { time: 61, text: "Enthan anbe... un vazhiyil nan varuvene..." }
    ]
  },
  {
    id: "pavazha-malli-bminor",
    title: "Pavazha Malli (B♭ Minor - BPM 69)",
    artist: "Sai Abhyankkar",
    album: "Pavazha Malli (Special Pitch)",
    duration: "4:56",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293185/Pavazha_Malli_B__minor__bpm_69_bpkwdp.mp3",
    cover: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&h=300&fit=crop&q=80",
    color: "#3a2d54",
    category: "Sai Abhyankkar Hits",
    liked: false,
    lyrics: [
      { time: 0, text: "🎵 Pavazha Malli (B♭ Minor Slowed & Reverb) 🎵" },
      { time: 10, text: "[Heavy bass and ambient synth pads swelling]" },
      { time: 25, text: "Oru maalai neram... mazhai saarum podhu..." },
      { time: 38, text: "Un vizhiyai paarthu nan vizhithu ponene..." },
      { time: 50, text: "Pavazha malli vaasam un koonthalil veesiyadho..." },
      { time: 62, text: "En nenjil un kaadhal puthu sangeetham paadiyadho..." },
      { time: 75, text: "🎵 [Deep ambient drop with BPM 69 rhythm] 🎵" }
    ]
  },
  {
    id: "jawan-theme",
    title: "Jawan Prevue Theme",
    artist: "Anirudh Ravichander",
    album: "Jawan (OST)",
    duration: "2:08",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293183/Jawan_Prevue_Theme_-_Jawan_320_Kbps_akq5im.mp3",
    cover: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&h=300&fit=crop&q=80",
    color: "#7d0b11",
    category: "Mass Beats",
    liked: false,
    lyrics: [
      { time: 0, text: "💥 Jawan Prevue Theme - Anirudh 💥" },
      { time: 4, text: "Aiyyo! [Epic brass blare]" },
      { time: 8, text: "Ready...? [Massive electronic beat drop]" },
      { time: 14, text: "Here comes the King! Watch out!" },
      { time: 20, text: "[Fast rhythmic heavy metal strings]" },
      { time: 32, text: "Thunderous drums pounding!" },
      { time: 45, text: "Who am I? Good...? Bad...? Or Ugly?" },
      { time: 55, text: "There is a fire burning deep inside!" },
      { time: 68, text: "[Epic high-tempo choir chanting]" },
      { time: 90, text: "Jawan! The unstoppable force!" }
    ]
  },
  {
    id: "powerhouse-disco",
    title: "Powerhouse x Disco",
    artist: "DJ Mashup / BGM",
    album: "Club Classics Vol 1",
    duration: "1:10",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293183/Powerhouse_x_Disco_1_hys5ci.mp3",
    cover: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&h=300&fit=crop&q=80",
    color: "#d9a014",
    category: "Club Remixes",
    liked: false,
    lyrics: [
      { time: 0, text: "🪩 Powerhouse x Disco Remix 🪩" },
      { time: 2, text: "[Funk bassline grooving in]" },
      { time: 8, text: "Unleash the disco power!" },
      { time: 12, text: "Feel the retro vibes pumping!" },
      { time: 20, text: "Pump it up! Keep the beat moving!" },
      { time: 35, text: "[Disco dynamic synthesis and handclaps]" },
      { time: 48, text: "One, two, three, let's go!" },
      { time: 52, text: "[High-energy electro synth breakdown]" }
    ]
  },
  {
    id: "pavazha-malli-cut",
    title: "Pavazha Malli (Short Cut - 58s)",
    artist: "Sai Abhyankkar",
    album: "Pavazha Malli (Teaser Edition)",
    duration: "0:58",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293182/Pavazha_Malli__cut_58sec_xe2lu8.mp3",
    cover: "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=300&h=300&fit=crop&q=80",
    color: "#1b4f35",
    category: "Sai Abhyankkar Hits",
    liked: false,
    lyrics: [
      { time: 0, text: "🌸 Pavazha Malli (Teaser Edit) 🌸" },
      { time: 4, text: "Oru maalai neram... mazhai saarum podhu..." },
      { time: 12, text: "Un vizhiyai paarthu nan vizhithu ponene..." },
      { time: 22, text: "Pavazha malli vaasam un koonthalil veesiyadho..." },
      { time: 32, text: "En nenjil un kaadhal puthu sangeetham paadiyadho..." },
      { time: 45, text: "🎵 [Beautiful flute outro fadeout] 🎵" }
    ]
  },
  {
    id: "kiliye-kiliye",
    title: "Kiliye Kiliye (Afrobeat Remix)",
    artist: "S. Janaki x The Independeners",
    album: "Retro Afro Fusion",
    duration: "2:50",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293181/Kiliye_Kiliye_-_Afrobeat_X_Kalyani_Priyadarshan_Video_The_Independeners_Aa_Raathri_S_Janaki_-_Saregama_Malayalam_mjlgbe.mp3",
    cover: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&h=300&fit=crop&q=80",
    color: "#0f62fe",
    category: "Club Remixes",
    liked: false,
    lyrics: [
      { time: 0, text: "🌴 Kiliye Kiliye (Afrobeat X Kalyani) 🌴" },
      { time: 6, text: "[Smooth Afrobeat shaker and conga groove]" },
      { time: 14, text: "Kiliye kiliye narumozhi kiliye..." },
      { time: 21, text: "Enthoru azhakanu nin chundiloru punchiri..." },
      { time: 28, text: "Aa raathri nammal kandathorthu paadunnu..." },
      { time: 35, text: "[Catchy modern bass kick with retro vocals]" },
      { time: 49, text: "Kiliye kiliye parannu vaa en anbe..." },
      { time: 56, text: "Kaathil melle choriyamo thanga sangeetham..." }
    ]
  },
  {
    id: "jolly-o-gymkhana",
    title: "Jolly O Gymkhana",
    artist: "Thalapathy Vijay & Anirudh",
    album: "Beast (Original Soundtrack)",
    duration: "3:28",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293181/Jolly-O-Gymkhana-MassTamilan.so_tpfs0m.mp3",
    cover: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=300&h=300&fit=crop&q=80",
    color: "#e01a4f",
    category: "Mass Beats",
    liked: false,
    lyrics: [
      { time: 0, text: "🥳 Jolly O Gymkhana - Beast 🥳" },
      { time: 4, text: "Rap-pap-pa... Jolly O Gymkhana!" },
      { time: 8, text: "Vandhaale jolly thaan... ponaale jolly thaan..." },
      { time: 13, text: "Life-u thaan konjam jolly-a eduthukka nanbaa!" },
      { time: 19, text: "Kavalai ellaam thoorathilae thalli vaingadaa..." },
      { time: 25, text: "Kondadi padunga, jolly-o-gymkhana!" },
      { time: 30, text: "Varlaam vaa varlaam vaa... sandhosham varattum..." },
      { time: 36, text: "Jolly o gymkhana! Enna nanbaa sweet-ah?" }
    ]
  },
  {
    id: "oh-butterfly",
    title: "Oh Butterfly (Live in Concert)",
    artist: "Ilaiyaraaja",
    album: "Ilaiyaraaja Truly Live in Chennai",
    duration: "5:17",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293180/Oh_Butterfly_Song___Ilaiyaraaja_s_Truly_Live_in_Concert_-_Chennai___Mercuri_Foundation_bSXkLWESXBY_xq2hyn.mp3",
    cover: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=300&h=300&fit=crop&q=80",
    color: "#7353ba",
    category: "Melodies & Love",
    liked: false,
    lyrics: [
      { time: 0, text: "🦋 Oh Butterfly - Maestro Ilaiyaraaja Live 🦋" },
      { time: 12, text: "[Audience roaring, live string orchestra starts]" },
      { time: 26, text: "Oh butterfly... butterfly... yen virindhai un siragai..." },
      { time: 40, text: "Vaan veedhiyil nee parakka en tholil amarnthayo..." },
      { time: 54, text: "En kaadhalin thoodhanaai unnai anupinenae..." },
      { time: 68, text: "[Live audience clapping along with acoustic guitar]" },
      { time: 82, text: "Maalai poongatre... pattu paadamma..." }
    ]
  },
  {
    id: "pavazha-malli-phonk",
    title: "Pavazha Malli (Phonk Remix)",
    artist: "Thi Tivi Records",
    album: "Phonk Express Tamil",
    duration: "1:24",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293181/Pavazha_Malli_Phonk_Thi_Tivi_Records_etyizj.mp3",
    cover: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&h=300&fit=crop&q=80",
    color: "#e23c12",
    category: "Club Remixes",
    liked: false,
    lyrics: [
      { time: 0, text: "🏎️ Pavazha Malli Phonk Drift Edition 🏎️" },
      { time: 2, text: "[Heavy cowbell starting... warning: high bass!]" },
      { time: 8, text: "[Aggressive drift phonk beat drop!]" },
      { time: 15, text: "Pavazha malli... [chopped vocal samples]" },
      { time: 22, text: "[Pulsating 808 sub bass lines]" },
      { time: 35, text: "Un vizhiyai paarthu nan... [phonk distorted vocal]" },
      { time: 50, text: "[Double time phonk cowbell ride]" }
    ]
  },
  {
    id: "ranchi-dhoni",
    title: "From Ranchi He Rose (Dhoni BGM)",
    artist: "Sushin Shyam",
    album: "Cricket Tributes",
    duration: "2:46",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293180/From_Ranchi_he_rose_with_a_fire_in_his_jtgo7x.mp3",
    cover: "https://images.unsplash.com/photo-1540747737956-3787293e55e8?w=300&h=300&fit=crop&q=80",
    color: "#004b23",
    category: "Cinematic BGMs",
    liked: false,
    lyrics: [
      { time: 0, text: "🏏 Dhoni Tribute: From Ranchi He Rose 🏏" },
      { time: 5, text: "[Atmospheric wind chimes and soft keyboard]" },
      { time: 15, text: "From Ranchi he rose, with a fire in his eyes..." },
      { time: 25, text: "A ticket collector, chasing the skies..." },
      { time: 38, text: "[Acoustic guitar strums swelling into epic strings]" },
      { time: 50, text: "MSD... Captain Cool... leading the nation!" },
      { time: 65, text: "[Massive stadium cheers, electronic pad rhythm]" },
      { time: 85, text: "He finished it off in style! A magnificent strike into the crowd!" }
    ]
  },
  {
    id: "vizhi-veekura",
    title: "Vizhi Veekura (Short Edit)",
    artist: "Sai Abhyankkar",
    album: "Vizhi Veekura - Single",
    duration: "3:39",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293180/__SaiAbhyankkar_-_Vizhi_Veekura_Music_Video___Saanve_Megghana__Sai_Smriti_Adesh__Thejo__Think_Indie__cut_219sec_hpfilj.mp3",
    cover: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=300&h=300&fit=crop&q=80",
    color: "#d62246",
    category: "Sai Abhyankkar Hits",
    liked: false,
    lyrics: [
      { time: 0, text: "👀 Vizhi Veekura - Sai Abhyankkar 👀" },
      { time: 6, text: "[Slick upbeat synthpop bassline]" },
      { time: 16, text: "Vizhi veekura kanavugalaal unnai thodukiren..." },
      { time: 25, text: "Pudhithaaga oru vazhiyil nanum nadakiren..." },
      { time: 35, text: "En thozhai thottu pesum megamai maaraayo..." },
      { time: 44, text: "Kaadhal enum vaanathil nan midhakkirenae..." },
      { time: 55, text: "[Upbeat dance transition with vocal chops]" }
    ]
  },
  {
    id: "oorum-blood",
    title: "Oorum Blood (Unplugged)",
    artist: "Anirudh Ravichander",
    album: "Leo (Acoustic Sessions)",
    duration: "2:10",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293180/Oorum_Blood_Unplugged_zfnud8.mp3",
    cover: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=300&h=300&fit=crop&q=80",
    color: "#590d22",
    category: "Melodies & Love",
    liked: false,
    lyrics: [
      { time: 0, text: "🩸 Oorum Blood (Unplugged Acoustic) 🩸" },
      { time: 4, text: "[Warm acoustic guitar strumming softly]" },
      { time: 12, text: "Engeyum oorum blood... enna seiya pogiraai..." },
      { time: 24, text: "Oru paadhaiyil... thaniyaaga sentraenae..." },
      { time: 36, text: "Un ninaivugal ennai thodaruthu anbe..." },
      { time: 48, text: "[Guitar harmonics and gentle vocal humming]" },
      { time: 60, text: "Oorum blood... un kaadhal enakkul dhaan..." }
    ]
  },
  {
    id: "dheema",
    title: "Dheema",
    artist: "Anirudh Ravichander",
    album: "Love Insurance Kompany (LIK)",
    duration: "3:40",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293179/Dheema_Video_Song_Tamil_Love_Insurance_Kompany_Pradeep_Ranganathan_Anirudh_Vignesh_Shivan_x8xm8j.mp3",
    cover: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&h=300&fit=crop&q=80",
    color: "#008080",
    category: "Melodies & Love",
    liked: false,
    lyrics: [
      { time: 0, text: "💎 Dheema - Love Insurance Kompany 💎" },
      { time: 4, text: "[Catchy electronic pop synth loop]" },
      { time: 14, text: "Dheema... dheema... en nenjil nee thaanama..." },
      { time: 22, text: "Unnai paartha nodiyil nan thondruvene..." },
      { time: 30, text: "Kaadhal insurance naanum eduppene..." },
      { time: 38, text: "Un vizhigalukkulae ennai pathivu seiven..." },
      { time: 46, text: "En dheema... anbe... nee thaan en thozhi..." },
      { time: 54, text: "[High-energy romantic electronic dance beat]" }
    ]
  },
  {
    id: "adaavadi",
    title: "Adaavadi",
    artist: "Anirudh Ravichander",
    album: "Love Insurance Kompany (LIK)",
    duration: "3:30",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293177/Adaavadi_Music_Video___LIK___Pradeep_Ranganathan___Anirudh_l_Vignesh_Shivan___Krithi_Shetty_pqiyjo.mp3",
    cover: "https://images.unsplash.com/photo-1487180142328-054b783fc471?w=300&h=300&fit=crop&q=80",
    color: "#4a4e69",
    category: "Melodies & Love",
    liked: false,
    lyrics: [
      { time: 0, text: "🔥 Adaavadi - LIK 🔥" },
      { time: 5, text: "[Upbeat percussion and acoustic guitars]" },
      { time: 15, text: "Adaavadi pannuraai... en manadhai parikkiraai..." },
      { time: 24, text: "Oru muraiavadhu ennai paarthu pesamma..." },
      { time: 33, text: "Un kurumbu paarvaiyaal ennai kollaadhe..." },
      { time: 42, text: "Adaavadi seiyum en kaadhal devathaiye..." },
      { time: 52, text: "[Fun electronic flute and whistling hook]" }
    ]
  },
  {
    id: "dude-ost",
    title: "Dude OST - Interval BGM",
    artist: "BGM Creator",
    album: "Dude Original Soundtrack",
    duration: "1:44",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293178/Dude_OST_-_Interval_Background_Score___FREE_DOWNLOAD_RC7Hl3IfskU_icttbi.mp3",
    cover: "https://images.unsplash.com/photo-1483412033650-1015ddeb83d1?w=300&h=300&fit=crop&q=80",
    color: "#2c3e50",
    category: "Cinematic BGMs",
    liked: false,
    lyrics: [
      { time: 0, text: "🎬 Dude OST - Epic Interval Score 🎬" },
      { time: 5, text: "[Heavy atmospheric sub-bass rising]" },
      { time: 15, text: "[Tension piano keys playing a repetitive loop]" },
      { time: 30, text: "[Epic brass stabs dropping with heavy industrial drums]" },
      { time: 50, text: "[Violin orchestra takes over the emotional melody]" },
      { time: 75, text: "[Full cinematic epic breakdown with guitar distortion]" }
    ]
  },
  {
    id: "o-maara",
    title: "O Maara",
    artist: "A.R. Rahman",
    album: "Thug Life (OST)",
    duration: "3:43",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293177/O_Maara_-_Lyrical_Thug_Life_Kamal_Haasan_Mani_Ratnam_STR_Trisha_AR_Rahman_RKFI_MT_j0ofrb.mp3",
    cover: "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=300&h=300&fit=crop&q=80",
    color: "#38040e",
    category: "Melodies & Love",
    liked: false,
    lyrics: [
      { time: 0, text: "👑 O Maara - Maestro A.R. Rahman 👑" },
      { time: 5, text: "[Ethereal ambient strings and flute]" },
      { time: 14, text: "O Maara... en Maara..." },
      { time: 24, text: "Thug life payanam idhu... nizhalum un thunaiye..." },
      { time: 35, text: "Tholai thooram kaanbadhu puthu vazhi kaattumae..." },
      { time: 48, text: "[Divine female choral harmonies swell]" },
      { time: 60, text: "O Maara... vidiyalai noki nadappoma..." }
    ]
  },
  {
    id: "badass-leo",
    title: "Badass",
    artist: "Anirudh Ravichander",
    album: "Leo (Original Soundtrack)",
    duration: "3:49",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293176/Leo_-_Badass_Video_Thalapathy_Vijay_Anirudh_Ravichander_rebalanced_uac2rb.mp3",
    cover: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=300&h=300&fit=crop&q=80",
    color: "#ff4d00",
    category: "Mass Beats",
    liked: false,
    lyrics: [
      { time: 0, text: "💥 Badass Maan: Leo Das Anthem 💥" },
      { time: 3, text: "Mr. Leo Das is a Badass!" },
      { time: 8, text: "[Explosive guitar riffs and electronic synths]" },
      { time: 18, text: "Thalapathy! [Heavy sub-bass kicks in]" },
      { time: 24, text: "Oru singam theriya pogudhu... vazhiyila thalli nillu!" },
      { time: 32, text: "Leo Leo Leo... Badass!" },
      { time: 40, text: "Adra Sakka! [Furious techno breakdown]" },
      { time: 55, text: "He is a beast! Watch him tear it down!" },
      { time: 68, text: "Rathira kootukulle... singam dhaan vettaiyadum!" }
    ]
  },
  {
    id: "pavazha-malli-unplugged",
    title: "Pavazha Malli (Unplugged)",
    artist: "Sai Abhyankkar ft. Shruti Haasan",
    album: "Pavazha Malli Special",
    duration: "3:42",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293174/SaiAbhyankkar_-_Pavazha_Malli_Unplugged___Shruti_Haasan___Vivek___Think_Indie_ghprrt.mp3",
    cover: "https://images.unsplash.com/photo-1516280440614-37939bbacd6a?w=300&h=300&fit=crop&q=80",
    color: "#1b4f35",
    category: "Sai Abhyankkar Hits",
    liked: false,
    lyrics: [
      { time: 0, text: "🌸 Pavazha Malli (Acoustic Unplugged) 🌸" },
      { time: 5, text: "[Intimate piano keys and soft shaker]" },
      { time: 14, text: "Oru maalai neram... mazhai saarum podhu..." },
      { time: 24, text: "[Shruti Haasan's beautiful melodic vocals join]" },
      { time: 35, text: "Un vizhiyai paarthu nan vizhithu ponene..." },
      { time: 46, text: "Pavazha malli vaasam un koonthalil..." },
      { time: 58, text: "[Harmonized dual vocals with warm acoustic guitar]" }
    ]
  },
  {
    id: "mobsta",
    title: "Mobsta",
    artist: "KoshalWorld",
    album: "Mobsta - Single",
    duration: "2:54",
    url: "https://res.cloudinary.com/df2rueeeg/video/upload/v1780293174/Mobsta_KoshalWorld.Com_vz6n5h.mp3",
    cover: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&h=300&fit=crop&q=80",
    color: "#100007",
    category: "Cinematic BGMs",
    liked: false,
    lyrics: [
      { time: 0, text: "🕶️ Mobsta - KoshalWorld 🕶️" },
      { time: 5, text: "[Sleek dark electronic synth bassline]" },
      { time: 14, text: "Welcome to the underworld... Mobsta!" },
      { time: 22, text: "[Hip hop trap beat drop, heavy snare]" },
      { time: 35, text: "Walking like a mob boss, cash in my pocket..." },
      { time: 48, text: "Can't stop, won't stop. We own this city!" },
      { time: 62, text: "[Fast synth melody transition]" }
    ]
  }
];
